### ISSUE TITLE
Add a loading spinner when the chart is rendering

### ISSUE THREAD

**Issue by vivekratnavel** [uwdata/vega-lite#534]
Is there an event which will get triggered once the chart is loaded?

With large datasets, this is a necessity.

**Comment by kanitw** [comment]
Thank for creating issue.  

This should be a UI-level issue.  As a toolkit, Vega-lite itself should not implement this by itself, so that higher level application can customize their own spinner implementation. 

I'm filing this as an issue in vega-lite-ui instead. https://github.com/uwdata/vega-lite-ui/issues/52

**Comment by kenmendez** [comment]
The above link is dead. Did this issue ever get resolved? I'm trying to pull this info out of vega embed and am struggling.

**Comment by kanitw** [comment]
If there is a desired behavior for vega-embed, please file an issue in the repo. Thanks!
