### ISSUE TITLE
De-compiling vg spec to vl spec

### ISSUE THREAD

**Issue by vinodpahuja** [uwdata/vega-lite#540]
Hi,

I was playing around with some use case to convert few basic encoding to vega spec. Later I need to modify those vega spec. But I didn't find any way to convert it back to vl spec. I am stuck with manually modify the vega spec.

Is there any way that can de-compile vega spec to vl spec.?

**Comment by kanitw** [comment]
By design, Vega is more expressive than Vega-lite.  Therefore, one can't write a function that decompiles  Vega to Vega-lite function that works with any Vega specification.  

If you only modify config values without modifying the Vega spec structure.  In theory, it should map back to Vega-lite nicely.  But if you're doing these minor fiddles anyway, I suggest that you modify those properties directly from Vega-lite.   We haven't written a documentation for Vega-lite spec but if you want to dig into code to see what properties are available, take a look at [Vega-lite JSON schema in schema.js starting from line 727](https://github.com/uwdata/vega-lite/blob/master/src/schema/schema.js#L727).   That should give you a list of all available properties.
